from ..bases.MappingConstants import MappingConstants


class Opcode(MappingConstants):
    PING = 1
    LOG = 5
    SEND_USER_AGENT = 6
    PROFILE = 16
    START_SMS_AUTH = 17
    CHECK_SMS_CODE = 18
    AUTHORIZE = 19
    LOGOUT = 20
    CONFIG = 22
    SYNC = 21
    CONFIRM_REGISTRATION = 23
    GET_CONTACT = 32
    CONTACT_UPDATE = 34
    # CHAT_INFO = 48
    CONTACT_INFO_BY_PHONE = 46
    GET_CHAT = 48
    GET_CHAT_MESSAGES_PER_CHUNK = 49
    READ_MESSAGE = 50
    DELETE_CHAT = 52
    FETCH_CHATS = 53
    CHAT_UPDATE = 55
    JOIN_GROUP = 57
    LEAVE_CHAT = 58
    CHAT_MEMBERS = 59
    SEND_MESSAGE = 64
    DELETE_MESSAGE = 66
    EDIT_MESSAGE = 67
    GET_MESSAGES = 71
    OPERATION_WITH_CHAT_MEMBER = 77
    CREATE_PHOTO = 80
    CREATE_VIDEO = 82
    GET_VIDEO = 83
    GET_FILE = 88
    CREATE_FILE = 87
    LINK_INFO = 89
    SESSIONS_INFO = 96
    SESSIONS_CLOSE = 97
    SET_PASSWORD = 107
    SET_HINT = 108
    SET_EMAIL = 109
    VERIFY_EMAIL = 110
    SET_2_FACTOR = 111
    GET_TRACKID_FOR2FA = 112
    AUTH_CHECK_PASSWORD = 113
    RESOLVE_2FA = 115
    PUSH_NOTIFICATION = 128
    TYPING_NOTIFICATION = 129
    MESSAGE_READ_NOTIFICATION = 130
    PRESENCE_NOTIFICATION = 132
    CHAT_NOTIFICATION = 135
    MESSAGE_DELETE_NOTIFICATION = 142
    MESSAGE_REACTIONS_CHANGED = 155
    MESSAGE_REACTION_UPDATE = 156
    ADD_REACTION = 178
    REMOVE_REACTION = 179
    GET_REACTIONS = 180
    FOLDERS_GET = 272
    FOLDERS_UPDATE = 274
    FOLDERS_DELETE = 276
    METADATA_FOR_LOGIN = 288
    TRACK_LOGIN = 289
    AUTH_QR_APPROVE = 290
    GET_USER_DATA = 291
    VOTE_POLL = 304


class Cmd(MappingConstants):
    REQUEST = 0
    RESPONSE = 1
